// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuEJfZMIPTksFq4X0Jc0aOENLo3mBoOm8',
    appId: '1:358939117466:web:f44d93b1d69e3fa6885c23',
    messagingSenderId: '358939117466',
    projectId: 'smartwarehousemanager-1523c',
    authDomain: 'smartwarehousemanager-1523c.firebaseapp.com',
    storageBucket: 'smartwarehousemanager-1523c.firebasestorage.app',
    measurementId: 'G-7D3BEWSFNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBujvW9gJfI3-460MQj_31o5hURP1oBAiA',
    appId: '1:358939117466:android:900e31e5417589a7885c23',
    messagingSenderId: '358939117466',
    projectId: 'smartwarehousemanager-1523c',
    storageBucket: 'smartwarehousemanager-1523c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLV53SJHtKhmHTCLk39cfL3bXiZenGxJA',
    appId: '1:358939117466:ios:eb4d1c2092d6959f885c23',
    messagingSenderId: '358939117466',
    projectId: 'smartwarehousemanager-1523c',
    storageBucket: 'smartwarehousemanager-1523c.firebasestorage.app',
    iosClientId: '358939117466-irvq1905768ugu68rkumgk9j9hfh65ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartWarehouseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLV53SJHtKhmHTCLk39cfL3bXiZenGxJA',
    appId: '1:358939117466:ios:eb4d1c2092d6959f885c23',
    messagingSenderId: '358939117466',
    projectId: 'smartwarehousemanager-1523c',
    storageBucket: 'smartwarehousemanager-1523c.firebasestorage.app',
    iosClientId: '358939117466-irvq1905768ugu68rkumgk9j9hfh65ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartWarehouseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuEJfZMIPTksFq4X0Jc0aOENLo3mBoOm8',
    appId: '1:358939117466:web:6271d38464c96fce885c23',
    messagingSenderId: '358939117466',
    projectId: 'smartwarehousemanager-1523c',
    authDomain: 'smartwarehousemanager-1523c.firebaseapp.com',
    storageBucket: 'smartwarehousemanager-1523c.firebasestorage.app',
    measurementId: 'G-PD8JDMR1CE',
  );

}